
const LOGIN_REQUEST = "LOGIN_REQUEST"   ;
const LOGIN_SUCCESS = "LOGIN_SUCCESS"   ;
const LOGIN_ERROR   = "LOGIN_ERROR"      ;
const USER_NOT_FOUND = "USER_NOT_FOUND"  ;
const INCORRECT_PASSWORD = "INCORRECT_PASSWORD" ;



export {
      LOGIN_REQUEST ,
      LOGIN_SUCCESS ,
      LOGIN_ERROR ,
      USER_NOT_FOUND ,
      INCORRECT_PASSWORD
}