

const FORGOT_REQUEST = "FORGOT_REQUEST" ;
const FORGOT_SUCCESS = "FORGOT_SUCCESS"  ;
const FORGOT_FAILED  = "FORGOT_FAILED"    ;
const REQUEST_SUCCESS  =  "REQUEST_SUCCESS"  ;
const REQUEST_FAILED   = "REQUEST_FAILED" ;
const PASSWORD_CHANGE_REQUEST  = "PASSWORD_CHANGE_REQUEST"


export  {
    FORGOT_REQUEST ,
    FORGOT_SUCCESS ,
    FORGOT_FAILED,
    REQUEST_SUCCESS ,
    REQUEST_FAILED ,
    PASSWORD_CHANGE_REQUEST
}